version: 2
updates:
  - package-ecosystem: composer
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: cron
      cronjob: 0 6 * * *
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
    cooldown:
      default-days: 7
